apiVersion: v1
kind: Service
metadata:
  name: {{ include "capstone-chart.fullname" . }}
  labels:
    {{- include "capstone-chart.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "capstone-chart.selectorLabels" . | nindent 6 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
